# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andydevs
email: andydevs1@gmail.com
description: >
  My website where I talk about things that I've learned and/or have 
  interest in (which is mostly computer related). I also add updates
  on projects that I'm working on
baseurl: ""
url: "http://localhost:4000"
twitter_username: andydevs1
github_username: andydevs

# Build settings
markdown: kramdown