# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andydevs
description: >
  I am a self-taught hobbyist programmer with proficiency in Python and Javascript.
  I'm currently pursuing a degree in Computer Engineering, while I also work on
  programming projects on the side. My website where I put updates on projects
  that I'm working on. I also write about things that I've learned and/or have
  interest in.
url: "http://andydevs.github.io"
baseurl: ""
github_username: andydevs

# Build settings
markdown: kramdown
plugins:
  - jekyll-font-awesome-sass
font-awesome:
  assets: true