# Muh website!
#
# Author:  Anshul Kharbanda
# Updated: 7 - 12 - 2020

# Site content
title: Andydevs
author: Anshul Kharbanda
description: >
  I am a hobbyist programmer with proficiency in Python and Javascript.
  This here website where I put updates on projects that I'm working on. 
  I also write about things that I've learned and/or have interest in.
copyright: 2020

# Links
links:
  - url: /projects
    text: Projects
  - url: /documents/anshul-kharbanda-2020-06.pdf
    text: Resume

# Social
social:
  github: andydevs
  linkedin: anshul-kharbanda-03433712b
  email: akanshul97@gmail.com

# Theme
remote_theme: andydevs/jekyll-theme-peaceful-gates