# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andydevs
email: andydevs1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My website where I update your faces on the projects I'm working on
  along with things that I've learned and/or have interest in.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: andydevs1
github_username: andydevs

# Build settings
markdown: kramdown