# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andydevs
email: andydevs1@gmail.com
description: >
  My website where I update your faces on the projects I'm working on.
  I also talk about things that I've learned and/or have interest in at the time
  (which is mostly computer related).
baseurl: ""
url: "https://andydevs.github.io"
twitter_username: andydevs1
github_username: andydevs

# Build settings
markdown: kramdown