# URL Settings
url: https://andydevs.github.io
baseurl: ''

# Site content
title: Andydevs
description: >
  I am a hobbyist programmer with proficiency in Python and Javascript.
  My website where I put updates on projects that I'm working on. I also
  write about things that I've learned and/or have interest in.

# Usernames
github_username: andydevs

# Theme bruh
remote_theme: andydevs/jekyll-theme-backwhite
